# Site settings
title: Iga Stępniak blog
email: iga.stepniak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Iga Stępniak and I am Java developer. Welcome to my blog!
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  igastepniak

# Build settings
markdown: kramdown
